---
title: "Trees for structure and support in Python"
subtitle: "PyCon Limerick 2020"
author: "Stephen McEntee"
date: "2020-02-29"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, metropolis, metropolis-fonts, custom.css]
    nature:
      titleSlideClass: [top, left]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "4:3"
    seal: true
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(knitr)
```

```{python, echo=FALSE, results='hide', engine.path='/home/develop/local/anaconda3/envs/py3/bin/python'}
from examples.one_line_tree import onelinetree, show_onelinetree_example
from examples.linked_list import LLnode
from vntree import Node
```


# Trees 1

This presentation is a high-level overview of tree data structures in computing.

With some lower-level details in Python.

#### presentation sides

* Link to slides https://qwilka.github.io/PyCon_Limerick_2020/ 
* The slides are created with [Remarkjs](https://remarkjs.com) and [Xaringan](https://slides.yihui.org/xaringan).
* Press **h** for help.
* References, links to source code, are in the presentation speaker notes (press **p**).


???

### references

1. Title page photo by [Luke Richardson](https://unsplash.com/s/photos/luke-richardson) on [Unsplash](https://unsplash.com/).



---

# Trees 2

### Trees are

* connected, hierarchical data structure consisting of units called `nodes`
* a node has <u>one</u> `parent` node in the level above and `child` nodes in the level below
* the tree starts at the `root` node, which uniquely has no parent
* trees are recursive, each child node is a sub-tree itself
* nodes without children represent the end of the tree, and are called `leaf` nodes



* social and political structures

???

* a lot of data falls naturally into a hierarchical tree structure.

  * countries and states
  * Organizational charts - organograms https://en.wikipedia.org/wiki/Organizational_chart


Even data that isn't naturally hierarchical can be transformed into a hierarchy.

social and political structures

### references


---

# List Tree

`list-node API: [<node name>: str, <data>: any, <child node>: list-node, ...]`

--

```{python, collapse=TRUE, results='markup', comment="", prompt=TRUE, R.options=list(prompt='>>> ', continue='>>> ')}
root = ["The World", {"population":7762609412}] # define tree root node 
europe = ["Europe", {"population":737000000}]  # define 1st child node
root.append(europe)  # append 1st child node to root node
namerica = ["North America", {"population":367914615}] # define 2nd child node
root.append(namerica)  # append 2nd child node to root node
scandinavia = ["Scandinavia", {"population":31000000}]
europe.append(scandinavia)
scandinavia.append( ["Denmark", {"population":5792202}] )
scandinavia.append( ["Sweden", {"population":10099265}] )
namerica.append( ["Canada", {"population":37742154}] ) 
```

--



```{python, collapse=TRUE, results='markup', comment="", prompt=TRUE, R.options=list(prompt='>>> ', continue='>>> ')}
pprint.pprint(root, indent=4, compact=True)
```

---

# One Line Tree

.pull-left[
```python
from collections import defaultdict

*def tree(): return defaultdict(tree)

root = tree()
root["The World"]
root["The World"]["population"] = 7762609412
root["The World"]["Europe"]
root["The World"]["Europe"]["Scandinavia"]
root["The World"]["Europe"]["Scandinavia"]["Denmark"]
root["The World"]["Europe"]["Scandinavia"]["Denmark"]["population"] = 5792202
root["The World"]["Europe"]["Scandinavia"]["Sweden"]
root["The World"]["Europe"]["Scandinavia"]["Sweden"]["population"] = 10099265
root["The World"]["Europe"]["Scandinavia"]["Norway"]
root["The World"]["Europe"]["Scandinavia"]["Norway"]["population"] = 5421241
root["The World"]["North America"]
root["The World"]["North America"]["Canada"]
root["The World"]["North America"]["Canada"]["population"] = 37742154

import json
print(json.dumps(root, indent=2))
```
]


--

.pull-right[
```{python, echo=FALSE, collapse=TRUE, results='markup', comment="", prompt=TRUE, R.options=list(prompt='>>> ', continue='>>> ')}
show_onelinetree_example()
```
]

???

### references

1. GitHub Gist [hrldcpr/tree.md](https://gist.github.com/hrldcpr/2012250) «One-line Tree in Python»
1. [Jeff Khupp 2013 article](https://jeffknupp.com/blog/2013/02/14/drastically-improve-your-python-understanding-pythons-execution-model/) describes a similar "auto-vivifying dictionary that operates like a trie"
1. Source code 

---

# A linked list in Python

.pull-left[
```python
class LLnode:
  def __init__(self, value, prev):
    self.prev = prev
    if prev:
        prev.append(self)
    self.next = () 
    self.value = value

  def append(self, newnode):
    self.next = newnode
    return newnode 

  def __iter__(self):
      ...

  def __reversed__(self):
      ... 

  def show(self):
      ... 
```
]

--

.pull-right[
```{python, collapse=TRUE, results='markup', comment="", prompt=TRUE, R.options=list(prompt='>>> ', continue='>>> ')}
first = LLnode('First Node', None)
sec = LLnode('Second Node', first)
third = LLnode(3, sec)
third.append( LLnode(4.0, None) )
```
{{content}}
]

--

```{python, collapse=TRUE, results='markup', comment="", prompt=TRUE, R.options=list(prompt='>>> ', continue='>>> ')}
for node in first:
    print(node.value)
```
{{content}}

--

```{python, collapse=TRUE, results='markup', comment="", prompt=TRUE, R.options=list(prompt='>>> ', continue='>>> ')}
for node in reversed(first):
    print(node.value)
```
{{content}}


???

### references

1. [Linked list](https://en.wikipedia.org/wiki/Linked_list) article on Wikipedia.
1. [linked_list.py](https://github.com/qwilka/PyCon_Limerick_2020/blob/master/examples/linked_list.py) source code on Github.

---

# Linked List - usage example

```{python, collapse=TRUE, results='markup', comment="", prompt=TRUE, R.options=list(prompt='>>> ', continue='>>> ')}
root = LLnode('Stephen Dedalus', None)
root.append(LLnode('Class of Elements')).append(LLnode('Clongowes Wood College')).append(LLnode('Sallins')).append(LLnode('County Kildare')).append(LLnode('Ireland')).append(LLnode('Europe')).append(LLnode('The World')).append(LLnode('The Universe'))
```

--

```{python, collapse=TRUE, results='markup', comment="", prompt=TRUE, R.options=list(prompt='>>> ', continue='>>> ')}
root.show()
```

--

- A linked list is a degenerate tree, following a single line of decent.

--

- It could be considered as a 'vertical' data structure.

--

- By contrast, an array could be regarded as a 'horizontal' data structure.


---

# A basic tree in Python

.pull-left[
```python
class Node:
  def __init__(self, name, parent, data=None):
    self.name = name
    self.children = []
    self.parent = parent
    if parent: parent.add_child(self)
    self.data = data

  def add_child(self, newnode):
    self.children.append(newnode)
    newnode.parent = self
    return newnode

  def remove_child(self, idx):
    return self.children.pop(idx)

  def copy(self):
    return copy.deepcopy(self) 

  def show(self):
      ... 
```
]

--

.pull-right[
```{python, collapse=TRUE, results='markup', comment="", prompt=TRUE, R.options=list(prompt='>>> ', continue='>>> ')}
root = Node('Root node', None)
child1 = Node('First child', root)
child2 = Node('2nd child', root, {"n":123})
child1.add_child( Node("grand-child", None, {}) )
```
{{content}}
]

--

```{python, collapse=TRUE, results='markup', comment="", prompt=TRUE, R.options=list(prompt='>>> ', continue='>>> ')}
for node in root:
    print(node.name)
```
{{content}}

--

```{python, collapse=TRUE, results='markup', comment="", prompt=TRUE, R.options=list(prompt='>>> ', continue='>>> ')}
for node in reversed(root):
    print(node.name)
```
{{content}}


???

### references

1. [Linked list](https://en.wikipedia.org/wiki/Linked_list) article on Wikipedia.
1. [linked_list.py](https://github.com/qwilka/PyCon_Limerick_2020/blob/master/examples/linked_list.py) source code on Github.



---
class: middle, center, inverse, notitletop

.large[https://qwilka.github.io/PyCon_Limerick_2020/]



???

### references

1. General references.
